apiVersion: v1
kind: ConfigMap
metadata:
  name: notify-config
  labels:
    {{- include "notify.labels" . | nindent 4 }}
data:
  notification-recipients: "admin@example.com,finance@example.com,+15551234567"
  review-notification-interval: "30"
  frontend-base-url: "http://localhost:3000"
  host: "0.0.0.0"
  port: "8006" 