apiVersion: v1
kind: Secret
metadata:
  name: notify-secrets
  labels:
    {{- include "notify.labels" . | nindent 4 }}
type: Opaque
data:
  database-url: {{ "postgresql://invoice_user:password@postgres:5432/invoice_db" | b64enc }}
  celery-broker-url: {{ "redis://redis:6379/0" | b64enc }}
  celery-result-backend: {{ "redis://redis:6379/0" | b64enc }}
  sendgrid-api-key: {{ "your_sendgrid_api_key_here" | b64enc }}
  twilio-account-sid: {{ "your_twilio_account_sid_here" | b64enc }}
  twilio-auth-token: {{ "your_twilio_auth_token_here" | b64enc }}
  twilio-from-number: {{ "+15551234567" | b64enc }} 