apiVersion: v1
kind: Service
metadata:
  name: {{ include "notify.fullname" . }}
  labels:
    {{- include "notify.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "notify.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api 