apiVersion: v2
name: grafana
version: 0.1.0
description: Grafana dashboards for InvoiceFlow observability
type: application
dependencies:
  - name: grafana
    version: "7.3.1"
    repository: "https://grafana.github.io/helm-charts" 