apiVersion: v1
kind: Secret
metadata:
  name: {{ include "billing.fullname" . }}
  labels:
    {{- include "billing.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ .Values.env.DATABASE_URL | b64enc | quote }}
  RABBITMQ_URL: {{ .Values.env.RABBITMQ_URL | b64enc | quote }}
  STRIPE_API_KEY: {{ .Values.env.STRIPE_API_KEY | b64enc | quote }}
  STRIPE_SUBSCRIPTION_ITEM_ID: {{ .Values.env.STRIPE_SUBSCRIPTION_ITEM_ID | b64enc | quote }} 