{{- include "invoiceflow-auth.validateConfig" . -}}
{{- if not .Values.secrets.jwtSecret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "invoiceflow-auth.fullname" . }}
  labels:
    {{- include "invoiceflow-auth.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  jwt-secret: {{ include "invoiceflow-auth.jwtSecret" . }}
  database-url: {{ include "invoiceflow-auth.databaseUrl" . }}
{{- end }} 