apiVersion: v1
kind: Secret
metadata:
  name: {{ include "exception.fullname" . }}-secrets
  labels:
    {{- include "exception.labels" . | nindent 4 }}
type: Opaque
data:
  database-url: {{ .Values.config.databaseUrl | b64enc | quote }}
  rabbitmq-url: {{ .Values.config.rabbitmqUrl | b64enc | quote }} 