apiVersion: v1
kind: Secret
metadata:
  name: {{ include "erp.fullname" . }}
  labels:
    {{- include "erp.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ .Values.env.DATABASE_URL | b64enc | quote }}
  RABBITMQ_URL: {{ .Values.env.RABBITMQ_URL | b64enc | quote }}
  ERP_API_BASE_URL: {{ .Values.env.ERP_API_BASE_URL | b64enc | quote }}
  ERP_API_TOKEN: {{ .Values.env.ERP_API_TOKEN | b64enc | quote }} 