apiVersion: v2
name: prometheus
version: 0.1.0
description: Prometheus Operator stack for InvoiceFlow observability
type: application
dependencies:
  - name: kube-prometheus-stack
    version: "55.5.0"
    repository: "https://prometheus-community.github.io/helm-charts" 