apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.anthropic.name }}
  labels:
    {{- include "query.labels" . | nindent 4 }}
type: Opaque
data:
  # Anthropic API key (base64 encoded)
  # This should be set during deployment with the actual API key
  {{ .Values.secrets.anthropic.key }}: {{ .Values.env.ANTHROPIC_API_KEY | b64enc }} 