apiVersion: v2
name: redis
description: Redis cluster for InvoiceFlow Query Service
type: application
version: 0.1.0
appVersion: "7.0"
dependencies:
  - name: redis
    version: "18.4.0"
    repository: "https://charts.bitnami.com/bitnami" 